### ISSUE TITLE
A single operating system

### ISSUE THREAD

**Issue by R3YW1N** [R3YW1N/Virus-for-win-10#1]
All viruses are designed only to run on Windows 10

**Comment by ragecandy31** [comment]
which virus is the easiest one to use?

**Comment by R3YW1N** [comment]
> which virus is the easiest one to usethe virus1.vbs is the easiest to use thanks to its code, and it is very easy to use.

BY:R3YW1N

**Comment by R3YW1N** [comment]
@ragecandy31 

the virus1.vbs is the easiest to use thanks to its code, and it is very easy to use.

thank you for your proposal
